export const  leadStatus = {
All: "all",
UNREAD: "unread",
REMINDER: "reminder",
PACKAGE: "package",
FOLLOW_UP: "followUp",
INTERESTED: "interested",
ATTENDED_DEMO: "attendedDemo",
CONFIRMED_PAYING: "confirmedPaying",
ADMITTED: "admitted",
REFUSED: "refused",
WASTE: "waste"
};


export const leadApiStatus = {
    ONE_FOLLOW_UP: "ONE_FOLLOW_UP",
    ONE_FOLLOW_UP_NOT_RESPONDING: "ONE_FOLLOW_UP_NOT_RESPONDING",
    TWO_INTERESTED_LOW: "TWO.1_INTERESTED_LOW",
    TWO_INTERESTED_MEDIUM: "TWO.2_INTERESTED_MEDIUM",
    TWO_INTERESTED_HIGH: "TWO.3_INTERESTED_HIGH",
    THREE_ATTENDED_DEMO: "THREE_ATTENDED_DEMO",
    FOUR_CONFIRMED_PAYING: "FOUR_CONFIRMED_PAYING",
    FIVE_ADMITTED: "FIVE_ADMITTED",
    NO_FOLLOWUP_REFUSED: "NO_FOLLOWUP_REFUSED",
    NO_FOLLOWUP_WASTE: "NO_FOLLOWUP_WASTE",
};